# Adapted from https://chatgpt.com/s/t_6941db0260a481918500c4a9a76d919c


name: Production of FAANG Report
run-name: ${{ github.actor }} is creating automated FAANG Report
on: 
  schedule:

  # From: https://crontab.guru/#0_8_*_*_6
  - cron: '0 8 * * 6'  # At 8 AM every Saturday
  workflow_dispatch:
permissions: write-all
jobs:
  Create_FAANG_Report:
    name: Create FAANG Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - run: |
          echo "Starting FAANG Report Creation"
      - name: FAANG Report Creation
        run: |
          ${GITHUB_WORKSPACE}/faang.py
      - run: |
          echo "FAANG Report Created Successfully"
      - name: "Commit and Push Changes"
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Automated update of FAANG Report" || echo "No changes to commit"
          git push origin HEAD:main
      - run: |
          echo "FAANG Report Changes Pushed Successfully"















